rtl8188eu_library = static_library(
  'rtl8188eu',
  'bb_table.c',
  'channel.c',
  'efuse.c',
  'firmware.c',
  'key.c',
  'calibration.c',
  'mac.c',
  'mac_table.c',
  'main.c',
  'power.c',
  'register.c',
  'rf_table.c',
  'rx.c',
  'tx_power.c',
  'tx.c',
  include_directories: u80211_drv_include,
)
